### PR TITLE
master: remove etcd-starter

### PR DESCRIPTION
**Pull request by crawford**
Change-Id: I719e6dba390c0cbf71a68a53864c79b1673d8659

### CODE REVIEW

**Comment by mischief** [comment]
LGTM

**Comment by marineam** [comment]
You are updating the release manifest, not master...

**Comment by crawford** [comment]
April fools? Let me fix that.

**Comment by crawford** [comment]
Updated. I'm removing it from the 633 build as well, and then I'll cherry-pick that change to the 633 branch.

**Comment by marineam** [comment]
@crawford ping?

**Comment by crawford** [comment]
@marineam updated

**Comment by marineam** [comment]
LGTM

**Pull request merged**
